SELECT 
    AUTHOR.AUTHOR_ID, 
    AUTHOR.AUTHOR_NAME, 
    BOOK.CATEGORY, 
    SUM(BOOK.PRICE * BOOK_SALES.SALES) AS TOTAL_SALES
FROM BOOK_SALES
JOIN BOOK ON BOOK_SALES.BOOK_ID = BOOK.BOOK_ID
JOIN AUTHOR ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
WHERE 
    BOOK_SALES.SALES_DATE >= '2022-01-01' AND 
    BOOK_SALES.SALES_DATE < '2022-02-01'
GROUP BY AUTHOR.AUTHOR_ID, BOOK.CATEGORY
ORDER BY AUTHOR.AUTHOR_ID, BOOK.CATEGORY DESC