SELECT A.YEAR, ROUND(AVG(A.PM_VAL1),2) AS 'PM10', ROUND(AVG(A.PM_VAL2),2) AS 'PM2.5'
FROM (
    SELECT YEAR(YM) AS YEAR, PM_VAL1, PM_VAL2
    FROM AIR_POLLUTION
    WHERE LOCATION2 = '수원'
) AS A
GROUP BY A.YEAR
ORDER BY A.YEAR