SELECT OS.USER_ID, OS.PRODUCT_ID
FROM (
    SELECT USER_ID, PRODUCT_ID, COUNT(*) CNT
    FROM ONLINE_SALE
    GROUP BY USER_ID, PRODUCT_ID
) AS OS
WHERE OS.CNT > 1
ORDER BY OS.USER_ID, OS.PRODUCT_ID DESC