SELECT PRODUCT_CODE, SUM(TOTAL_PRICE) AS SALES
FROM (
    SELECT B.PRODUCT_CODE, B.PRICE * A.SALES_AMOUNT AS TOTAL_PRICE
    FROM OFFLINE_SALE AS A
    JOIN PRODUCT AS B USING (PRODUCT_ID)
) AS C
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE