SELECT B.FOOD_TYPE, B.REST_ID, B.REST_NAME, B.FAVORITES
FROM (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE) AS A
JOIN REST_INFO AS B ON B.FOOD_TYPE = A.FOOD_TYPE AND B.FAVORITES = A.FAVORITES
ORDER BY FOOD_TYPE DESC