SELECT ANIMAL_ID, ANIMAL_INS.ANIMAL_TYPE, ANIMAL_INS.NAME
FROM ANIMAL_INS
JOIN ANIMAL_OUTS USING (ANIMAL_ID)
WHERE 
    SEX_UPON_INTAKE NOT LIKE 'Spayed%'
    AND SEX_UPON_INTAKE NOT LIKE 'Neutered%'
    AND (SEX_UPON_OUTCOME LIKE 'Spayed%'
    OR SEX_UPON_OUTCOME LIKE 'Neutered%')
ORDER BY ANIMAL_ID