SELECT CAR.CAR_TYPE, COUNT(*) AS CARS
FROM (SELECT * 
      FROM CAR_RENTAL_COMPANY_CAR 
      WHERE OPTIONS LIKE '%통풍시트%' 
      or OPTIONS LIKE '%열선시트%'
      or OPTIONS LIKE '%가죽시트%') AS CAR
GROUP BY CAR.CAR_TYPE
ORDER BY CAR.CAR_TYPE