SELECT 
    QUARTER,
    COUNT(*) AS ECOLI_COUNT
FROM 
    (SELECT (CASE 
    WHEN MONTH(DIFFERENTIATION_DATE) < 4 THEN '1Q' 
    WHEN MONTH(DIFFERENTIATION_DATE) > 3 AND MONTH(DIFFERENTIATION_DATE) < 7 THEN '2Q' 
    WHEN MONTH(DIFFERENTIATION_DATE) > 6 AND MONTH(DIFFERENTIATION_DATE) < 10 THEN '3Q' 
    WHEN MONTH(DIFFERENTIATION_DATE) > 9 THEN '4Q' 
    END) AS QUARTER
    FROM ECOLI_DATA
    ) AS A
GROUP BY A.QUARTER
ORDER BY 1