-- 코드를 입력하세요
SELECT FH.FLAVOR
FROM FIRST_HALF AS FH
JOIN 
    (SELECT FLAVOR, SUM(TOTAL_ORDER) AS JULY_ORDER
    FROM JULY
    GROUP BY FLAVOR) AS JULY
ON FH.FLAVOR = JULY.FLAVOR
ORDER BY FH.TOTAL_ORDER + JULY.JULY_ORDER DESC
LIMIT 3

