SELECT MP.MEMBER_NAME, RR.REVIEW_TEXT, DATE_FORMAT(RR.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE AS MP
JOIN REST_REVIEW AS RR USING (MEMBER_ID)
WHERE MP.MEMBER_ID = 
    (SELECT MEMBER_ID
    FROM REST_REVIEW 
    JOIN MEMBER_PROFILE USING (MEMBER_ID)
    GROUP BY MEMBER_ID
    ORDER BY COUNT(*) DESC
    LIMIT 1)
ORDER BY REVIEW_DATE, REVIEW_TEXT