SELECT M.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW AS R
JOIN MEMBER_PROFILE AS M ON R.MEMBER_ID = M.MEMBER_ID
WHERE R.MEMBER_ID IN 
    (SELECT t1.MEMBER_ID
    FROM (SELECT 
            MEMBER_ID, 
            COUNT(*),
            rank() over(ORDER BY COUNT(MEMBER_ID) DESC) AS ranks
        FROM REST_REVIEW
        GROUP BY MEMBER_ID) AS t1
    WHERE t1.ranks = 1)
ORDER BY R.REVIEW_DATE, R.REVIEW_TEXT;
