WITH MOST_REVIEW_COUNT_MEMBER AS (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(*) DESC
    LIMIT 1
)

SELECT 
    MP.MEMBER_NAME, 
    RR.REVIEW_TEXT, 
    DATE_FORMAT(RR.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MOST_REVIEW_COUNT_MEMBER AS MRCM
JOIN MEMBER_PROFILE AS MP ON MRCM.MEMBER_ID = MP.MEMBER_ID
JOIN REST_REVIEW AS RR ON MRCM.MEMBER_ID = RR.MEMBER_ID
ORDER BY REVIEW_DATE, REVIEW_TEXT
