SELECT II1.ITEM_ID, II1.ITEM_NAME, II1.RARITY
FROM ITEM_INFO AS II1
JOIN ITEM_TREE AS IT ON IT.ITEM_ID = II1.ITEM_ID
JOIN ITEM_INFO AS II2 ON IT.PARENT_ITEM_ID = II2.ITEM_ID
WHERE II2.RARITY = 'RARE'
ORDER BY II1.ITEM_ID DESC