SELECT CATEGORY, SUM(BOOK_SALES.SALES) AS TOTAL_SALES
FROM BOOK_SALES
JOIN BOOK ON BOOK_SALES.BOOK_ID = BOOK.BOOK_ID
WHERE 
    BOOK_SALES.SALES_DATE >= '2022-01-01' AND
    BOOK_SALES.SALES_DATE < '2022-02-01'
GROUP BY CATEGORY
ORDER BY CATEGORY